name: build

on:
  push:

permissions:
  actions: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the article PDF
    concurrency: showyourwork-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install Julia
        uses: julia-actions/install-juliaup@v2
        with:
          channel: '1'

      - name: Julia Cache
        uses: julia-actions/cache@v2
  
      - name: Build the article PDF
        id: build
        with:
          showyourwork-spec: git+https://github.com/showyourwork/showyourwork
          conda-cache-number: 1
        uses: showyourwork/showyourwork-action@main
        env:
          SANDBOX_TOKEN: ${{ secrets.SANDBOX_TOKEN }}
          OVERLEAF_EMAIL: ${{ secrets.OVERLEAF_EMAIL }}
          OVERLEAF_PASSWORD: ${{ secrets.OVERLEAF_PASSWORD }}

